name: crypto-forecast2
channels:
  - defaults
  - conda-forge
  - anaconda-cloud
dependencies:
  - python=3.7
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - statsmodels
  - matplotlib
  - pip
  - joblib
  - tensorflow
  - pip:
    - git+https://github.com/g8a9/pyti.git@master
    - imbalanced-learn
    - git+https://github.com/RedLicorice/sklearn-genetic.git@master
    - git+https://github.com/hyperopt/hyperopt-sklearn.git@master
    - xgboost
    - enlighten
    - openpyxl
