name: crypto-forecast
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - keras
  - statsmodels
  - matplotlib
  - tensorflow
  - seaborn
  - imbalanced-learn
  - pip
  - pip:
    - l3wrapper
    - git+https://github.com/g8a9/pyti.git@master
    - enlighten
