name: crypto-forecast
channels:
  - defaults
  - conda-forge
  - anaconda-cloud
dependencies:
  - python=3.7
  - numpy
  - pandas
  - scikit-learn
  - scipy
  #- keras
  - statsmodels
  - matplotlib
  #- tensorflow
  - seaborn
  #- imbalanced-learn
  - pip
  - joblib
  - plotly
  - pip:
    - l3wrapper
    - git+https://github.com/g8a9/pyti.git@master
    - enlighten
    - wrapt
    - openpyxl
    - sklearn-genetic
