name: crypto-forecast
channels:
  - defaults
  - conda-forge
  - anaconda-cloud
dependencies:
  - python=3.7
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - statsmodels
  - matplotlib
  - pip
  - joblib
  - pip:
    #- l3wrapper
    - git+https://github.com/g8a9/pyti.git@master
    #- openpyxl
    - imbalanced-learn
    - git+https://github.com/RedLicorice/sklearn-genetic.git@master
